key_params:
  d_length: 256
  blocks:
    block1:
      content: "10011001"
      quantity: 5
    block2:
      content: "1110101001"
      quantity: 3
    block3:
      content: "111101111"
      quantity: 6
    block4:
      content: "10101011101"
      quantity: 5
    block5:
      content: "110110101011101"
      quantity: 5